### ISSUE TITLE
Unable to use iitm ESM loader with @apollo/server

### ISSUE THREAD

**Issue by barryhagan** [DataDog/import-in-the-middle#31] opened 2023-09-02 02:47 UTC
## Expected Behavior

Using  import-in-the-middle/hook.mjs as a loader in an ESM project works when @apollo/server is used by the project.

## Actual Behavior

The node application failed to start.  The behavior varies based on the version of node in use.

Node v18: exit code 13
Node v20: exit code 1 with `SyntaxError: Unexpected token '*'`

## Steps to Reproduce the Problem

  1. clone https://github.com/barryhagan/iitm-apollo-server-repro
  2. npm i
  3. npm build
  4. npm run start

**Comment by bizob2828** [comment] 2023-09-11 17:17
It appears the issue is in Node 20 the exports are obtained via AST parsing.  Export * is not a valid export it just exports all data from the file it's importing.  I'm not sure of the best way to fix this because pre Node 20 this was a stateful wrap.  @Qard and @bengl any thoughts on the best way to fix?

**Comment by bizob2828** [comment] 2023-09-11 17:58
> Likely related to this: [DataDog/dd-trace-js#3595](https://github.com/DataDog/dd-trace-js/issues/3595)

I don't think this is related. The issue here is Node 20 and nuance to wrapping esm files with `export *` in them now that You can no longer call `Object.keys` on the imported package to get named exports

**Comment by jsumners-nr** [comment] 2023-12-14 13:31
This should be resolved by #43.

**Closed** 2023-12-15 17:05 UTC
