### ISSUE TITLE
Hooking a Module that Exports a Function Does not Hook a Callable Function

### ISSUE THREAD

**Issue by astorm** [DataDog/import-in-the-middle#18] opened 2022-08-15 06:42 UTC
## Expected Behavior

When hooking a module that exports a function, the exported object passed to the hook will also be a function. 

## Actual Behavior

When hooking a module that exports a function, the exported object passed to the hook is _not_ a function.

## Steps to Reproduce the Problem

We've noticed that, unlike `require-in-the-middle`, if you're trying to import a module that exports a _function_ object by default that the function won't be callable.  

That is -- if we install `fastify` and `import-in-the-middle` in a `type="module"` project

    % npm install import-in-the-middle
    % npm install fastify
    
and have a simple sample program that looks like this

    % cat index.js 
    import Fastify from 'fastify'
    import Hook from 'import-in-the-middle'

    Hook(['fastify'], (exported, name, baseDir) => {
      const fastifyInstance = exported()
    })

    const fastifyInstance = Fastify({
      logger:true
    })
    console.log(fastifyInstance)

    
We get an error when running the program.

    % node --loader=import-in-the-middle/hook.mjs index.js
    //...
      const fastifyInstance = exported()
                              ^

    TypeError: exported is not a function

With a `require-in-the-middle` hook, the `exported` variable is the callable function exported by the fastify module.

Is this something we could get `import-in-the-middle` doing?  Or are there :wave: reasons :wave: this isn't possible with either ESM modules or loader hooks?

For context -- This is a small isolated example of a larger problem we're trying to solve.  We have a piece of software with a large number of `require-in-the-middle` hooks.  We'd like to be able to provide our users with the same functionality if they happen to be using `import` statements while still supporting folks who are sticking with CommondJS modules at the same time.  The closer `import-in-the-middle`'s behavior is to `require-in-the-middle` the less we need branching code or refactoring of our existing hooks.

## Specifications

  - Version: 1.3.0
  - Platform: all
  - Subsystem: ?

**Comment by rochdev** [comment] 2022-08-16 21:29
I'm not 100% sure if this is related, but I think the issue is that the code handling this has not yet been moved to iitm: https://github.com/DataDog/dd-trace-js/blob/6eeb958b5638281a89f4e7d7e03d5f66aebe8547/packages/datadog-instrumentations/src/helpers/hook.js#L25-L34

**Comment by bengl** [comment] 2023-12-04 19:20
The `exported` object corresponds to the result of `import * as exported from 'module-name'` (i.e. a [namespace import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#namespace_import)), and so if a module has default exports (as `fastify` does), then that can be accessed with `exported.default`.

I'll close this since it's just a matter of using that `.default` property. Please feel free to comment here again if this doesn't resolve it for you.

**Closed by bengl** 2023-12-04 19:20 UTC
